Panel\PanelBundle\Entity\Bancos:
    type: entity
    table: bancos
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 100
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
