Panel\PanelBundle\Entity\MediosPagoClientes:
    type: entity
    table: medios_pago_clientes
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: Id
            generator:
                strategy: IDENTITY
        idCliente:
            type: integer
            unsigned: false
            nullable: true
            column: id_cliente
        idMedio:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: id_medio
    lifecycleCallbacks: {  }
