Panel\PanelBundle\Entity\Recovery:
    type: entity
    table: recovery
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        fecha:
            type: datetime
            nullable: true
        usuario:
            type: string
            length: 50
            fixed: false
            nullable: true
        clave:
            type: string
            length: 100
            fixed: false
            nullable: true
        password:
            type: string
            length: 100
            fixed: false
            nullable: true
        estado:
            type: string
            length: 20
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
