Panel\PanelBundle\Entity\Respuestas:
    type: entity
    table: respuestas
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: Id
            generator:
                strategy: IDENTITY
        idTipo:
            type: integer
            unsigned: false
            nullable: true
            column: id_tipo
        respuesta:
            type: string
            length: 100
            fixed: false
            nullable: true
        descripcion:
            type: string
            length: 255
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
