Panel\PanelBundle\Entity\TiposFacturas:
    type: entity
    table: tipos_facturas
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: Id
            generator:
                strategy: IDENTITY
        tipo:
            type: string
            length: 30
            fixed: false
            nullable: true
        descripcion:
            type: string
            length: 255
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
