Panel\PanelBundle\Entity\TiposPlan:
    type: entity
    table: tipos_plan
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: Id
            generator:
                strategy: IDENTITY
        plan:
            type: string
            length: 30
            fixed: false
            nullable: true
        descripcion:
            type: string
            length: 255
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
